name: Web Frontend CI Pipeline on PUSH
on: [push]

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout ✅
        uses: actions/checkout@v3

      - name: Setup 🏗
        uses: actions/setup-node@v3

      - name: Install ⚙️
        run: npm ci

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test
